[config]
version_check = false
caching = true



[templates.foot]
input_path = "./templates/foot-colors.ini"
output_path = "~/.config/foot/foot-colors.ini"

[templates.ghostty]
input_path = './templates/ghostty-colors'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.yazi]
input_path = './templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'
