# : Manager [[[

[mgr]
cwd = { fg = "#e5e1e9" }

# Tab
tab_active = { fg = "#31285f", bg = "#c9beff", bold = true }
tab_inactive = { fg = "#e6deff", bg = "#1c1149" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff72a5", bg = "#ff72a5" }
marker_cut = { fg = "#ffd8e6", bg = "#ffd8e6" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#edb8cd", bg = "#edb8cd" }

# Count
count_copied = { fg = "#301120", bg = "#ffd8e6" }
count_cut = { fg = "#301120", bg = "#ffd8e6" }
count_selected = { fg = "#31285f", bg = "#edb8cd" }

# Border
border_symbol = " "
border_style  = { fg = "#c9beff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#31285f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c9beff", fg = "#31285f", bold = true }
normal_alt  = { bg = "#48454e", fg = "#c9c5d0" }

# Select mode
select_main = { bg = "#c9c3dc", fg = "#312e41", bold = true }
select_alt  = { bg = "#48454e", fg = "#c9c5d0" }

# Unset mode
unset_main = { bg = "#edb8cd", fg = "#482535", bold = true }
unset_alt  = { bg = "#48454e", fg = "#c9c5d0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c9beff", bg = "#3a383e" }
progress_error = { fg = "#ffb4ab", bg = "#3a383e" }

# Permissions
permissions_t = { fg = "#7262a4" }
permissions_w = { fg = "#ce3e77" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3f84" }
permissions_s = { fg = "#7245ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c9beff" }
active = { fg = "#edb8cd", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#c9beff" }
value = { fg = "#e5e1e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#c9beff", bold = true, bg = "#141318" }
inactive = { fg = "#c9c3dc", bg = "#141318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c9beff", bg = "#31285f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c9beff" }
title = {}
hovered = { fg = "#ffd8e6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a383e" }
cand = { fg = "#c9beff" }
rest = { fg = "#31285f" }
desc = { fg = "#e5e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e5e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e5e1e9" }
run = { fg = "#e5e1e9" }
footer = { fg = "#312e41", bg = "#c9c3dc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#edb8cd" }
title_warn = { fg = "#c9beff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e5e1e9" },
    { name = "*/", fg = "#c9beff" },
]

# : ]]]
