# : Manager [[[

[mgr]
cwd = { fg = "#ede0d4" }

# Tab
tab_active = { fg = "#462a00", bg = "#f6bc70", bold = true }
tab_inactive = { fg = "#ffddb6", bg = "#2a1800" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#a8d06d", bg = "#a8d06d" }
marker_cut = { fg = "#d6e9ba", bg = "#d6e9ba" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bacd9f", bg = "#bacd9f" }

# Count
count_copied = { fg = "#121f03", bg = "#d6e9ba" }
count_cut = { fg = "#121f03", bg = "#d6e9ba" }
count_selected = { fg = "#462a00", bg = "#bacd9f" }

# Border
border_symbol = " "
border_style  = { fg = "#f6bc70" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#462a00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f6bc70", fg = "#462a00", bold = true }
normal_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

# Select mode
select_main = { bg = "#dec2a2", fg = "#3f2d17", bold = true }
select_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

# Unset mode
unset_main = { bg = "#bacd9f", fg = "#263514", bold = true }
unset_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f6bc70", bg = "#3f3830" }
progress_error = { fg = "#ffb4ab", bg = "#3f3830" }

# Permissions
permissions_t = { fg = "#ab773d" }
permissions_w = { fg = "#6f8b48" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#91c446" }
permissions_s = { fg = "#ff961d" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f6bc70" }
active = { fg = "#bacd9f", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#f6bc70" }
value = { fg = "#ede0d4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#f6bc70", bold = true, bg = "#18120c" }
inactive = { fg = "#dec2a2", bg = "#18120c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f6bc70", bg = "#462a00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f6bc70" }
title = {}
hovered = { fg = "#d6e9ba", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3f3830" }
cand = { fg = "#f6bc70" }
rest = { fg = "#462a00" }
desc = { fg = "#ede0d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ede0d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ede0d4" }
run = { fg = "#ede0d4" }
footer = { fg = "#3f2d17", bg = "#dec2a2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bacd9f" }
title_warn = { fg = "#f6bc70" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ede0d4" },
    { name = "*/", fg = "#f6bc70" },
]

# : ]]]
